### ISSUE TITLE
Srestore omode=pp returns error

### ISSUE THREAD

**Issue by xurich-xulaco** [WolframRhodium/muvsfunc#58]
After trying to see how well this srestore ran, I can't get to use any of the omode=pp1, pp2, or pp3 modes, none of them work, they get stuck and report following error code:

```
Script evaluation failed:
Python exception: Exceeds the limit (4300 digits) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit

Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 2886, in vapoursynth._vpy_evaluate
  File "src/cython/vapoursynth.pyx", line 2887, in vapoursynth._vpy_evaluate
  File "P3OP.py", line 91, in <module>
    deblend = muf.srestore(deint, omode='pp2')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Scripts/muvsfunc.py", line 8345, in srestore
    .format(i=scale(4, peak), peak=peak, j=scale(200, peak), k=scale(28, peak))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Exceeds the limit (4300 digits) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit
```

I'm really not sure what's wrong here or what I'm doing wrong, if it helps, I'm working with a clip with the following stats:

```
Width: 640
Height: 368
Frames: 2800
FPS: 30000/1001 (29.970 fps)
Format Name: YUV420P16
Color Family: YUV
Alpha: No
Sample Type: Integer
Bits: 16
SubSampling W: 1
SubSampling H: 1
```

**Comment by WolframRhodium** [comment]
Thanks! Please check the latest version.
